# Generated by Django 4.1 on 2022-10-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMalbec', '0002_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazar',
            name='imagen',
            field=models.ImageField(null=True, upload_to='bazar'),
        ),
        migrations.AddField(
            model_name='variedad',
            name='imagen',
            field=models.ImageField(null=True, upload_to='bebidas'),
        ),
    ]
