# Generated by Django 4.1 on 2022-10-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMalbec', '0003_bazar_imagen_variedad_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='bazar'),
        ),
        migrations.AlterField(
            model_name='variedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='bebidas'),
        ),
    ]
